// Package static embeds the compiled front-end assets into the binary
package static

import (
	"embed"
	"net/http"
)

// app.css is generated by `make css` and is gitignored.

//go:embed css/app.css
var files embed.FS

func Handler() http.Handler {
	h := http.FileServerFS(files)

	hfunc := func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "public, max-age=300")
		h.ServeHTTP(w, r)
	}

	handler := http.HandlerFunc(hfunc)
	return handler
}
