// Package static embeds the compiled front-end assets into the binary
package static

import (
	"embed"
	"net/http"
)

// app.css is generated by `make css` and is gitignored.
//
// js/htmx.min.js is vendored, not generated: htmx 2.0.7, from
// https://unpkg.com/htmx.org@2.0.7/dist/htmx.min.js. Replace the file to
// change the version.
//
// js/app.js is ours. It holds the behaviour htmx does not cover.

//go:embed css/app.css js/htmx.min.js js/app.js
var files embed.FS

func Handler() http.Handler {
	h := http.FileServerFS(files)

	hfunc := func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "public, max-age=300")
		h.ServeHTTP(w, r)
	}

	handler := http.HandlerFunc(hfunc)
	return handler
}
